name: Build Workflow
# Trigger this workflow on PRs
on:
  pull_request:
    types: [opened, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install
      - name: Test Next.js app
        run: npm run test
      - name: Build Next.js app
        run: npm run build
